{
 "title": "Flask Operator",
 "description": "Dashboard for the Flask Operator, powered by Juju.",
 "tags": [
  "flask",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(gunicorn_workers{}, app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gunicorn_requests{app=\"$app_name\"}"
    }
   ]
  },
  {
   "title": "Status Code Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gunicorn_response_code{app=\"$app_name\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(gunicorn_requests{app=\"$app_name\"}[1m])"
    }
   ]
  },
  {
   "title": "2XX Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(gunicorn_response_code{app=\"$app_name\", status=~\"2.*\"}) / sum(gunicorn_response_code{app=\"$app_name\"})",
     "legendFormat": "2XX Rate"
    }
   ]
  },
  {
   "title": "3XX Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(gunicorn_response_code{app=\"$app_name\", status=~\"3.*\"}) / sum(gunicorn_response_code{app=\"$app_name\"})",
     "legendFormat": "3XX Rate"
    }
   ]
  },
  {
   "title": "4XX Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(gunicorn_response_code{app=\"$app_name\", status=~\"4.*\"}) / sum(gunicorn_response_code{app=\"$app_name\"})",
     "legendFormat": "4XX Rate"
    }
   ]
  },
  {
   "title": "5XX Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(gunicorn_response_code{app=\"$app_name\", status=~\"5.*\"}) / sum(gunicorn_response_code{app=\"$app_name\"})",
     "legendFormat": "5XX Rate"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gunicorn_request_duration_sum{app=\"$app_name\"} / gunicorn_request_duration_count{app=\"$app_name\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Request Duration Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gunicorn_request_duration{app=\"$app_name\", quantile=\"0.5\"}",
     "legendFormat": "PR 50"
    },
    {
     "expr": "gunicorn_request_duration{app=\"$app_name\", quantile=\"0.9\"}",
     "legendFormat": "PR 90"
    },
    {
     "expr": "gunicorn_request_duration{app=\"$app_name\", quantile=\"0.99\"}",
     "legendFormat": "PR 99"
    }
   ]
  }
 ]
}